<a href="https://colab.research.google.com/github/oleg-zao/My-Home-Work-DLA-10.0/blob/main/hw_10_4_apply%2C_groupby%2C_pivot_table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/DS 10/supermarket_sales.csv')

df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Rating Category,Hour
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1,High,13
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6,High,10
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,Medium,13
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4,High,20
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3,Low,10

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [3]:
# Обчислюємо сумарний прибуток для кожного філіалу
total_profit_by_branch = df.groupby('Branch')['Total'].sum()

# Виводимо результат
print(total_profit_by_branch)

# Визначаємо філіал з найвищим прибутком
most_profitable_branch = total_profit_by_branch.idxmax()
print(f'Найприбутковіший філіал: {most_profitable_branch}')

Branch
A    106200.3705
B    106197.6720
C    110568.7065
Name: Total, dtype: float64
Найприбутковіший філіал: C

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [5]:
# Обчислюємо сумарний прибуток для кожного філіалу
total_profit_by_branch = df.groupby('Branch')['Total'].sum()

# Визначаємо філіал з найвищим прибутком
most_profitable_branch = total_profit_by_branch.idxmax()

# Знаходимо місто, де розташований цей філіал
city_of_most_profitable_branch = df[df['Branch'] == most_profitable_branch]['City'].unique()[0]


print(f'Найприбутковіший філіал: {most_profitable_branch}')
print(f'Місто: {city_of_most_profitable_branch}')

Найприбутковіший філіал: C
Місто: Naypyitaw

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [6]:
# Створюємо зведену таблицю
invoices_by_category = df.pivot_table(index='Branch', columns='Product line', values='Invoice ID', aggfunc='count')

display(invoices_by_category)

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [7]:
# Знаходимо філіал з найбільшою кількістю інвойсів для категорії "Electronic accessories"
most_invoices_branch = invoices_by_category['Electronic accessories'].idxmax()

# Виводимо результат
print(f'Місто: {most_invoices_branch}')

Місто: A

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

# Гіпотеза 1:
**Чи впливає оцінка покупця (Rating) на середній чек покупки (Total)?**

*Питання:* Чи залежить загальна сума покупки від того, наскільки високо покупець оцінив магазин?

*Ціль:* Зрозуміти, чи задоволені клієнти витрачають більше грошей і як це можна використовувати для підвищення рівня обслуговування та збільшення продажів.

# Гіпотеза 2:
**В який період дня (ранок, день чи вечір) клієнти витрачають більше грошей?**

*Питання:*
В який час доби фіксується найбільша сума покупок, і чи впливає це на загальну кількість покупок?

*Ціль:*
Оптимізувати маркетингові активності, акції або розпродажі, орієнтуючись на періоди пікових продажів.

# Гіпотеза 3:
**Чи існує зв'язок між типом клієнта (Customer type) та кількістю придбаних одиниць товару (Quantity)?**


*Питання:*
Чи постійні клієнти (Member) купують більше товарів у порівнянні з новими клієнтами (Normal)?

*Ціль:*
Розробити ефективніші програми лояльності або знижки для залучення нових клієнтів.

In [8]:
# Відповідь на Гіпотезу 1: Оцінка покупця та середній чек

# Обчислюємо середній чек для кожного рівня оцінки (Rating)
average_total_by_rating = df.groupby('Rating')['Total'].mean()


print(average_total_by_rating)

Rating
4.0     362.410364
4.1     211.128441
4.2     421.632273
4.3     331.006083
4.4     395.092147
           ...
9.6     328.956353
9.7     238.028250
9.8     261.943500
9.9     363.933281
10.0    416.070900
Name: Total, Length: 61, dtype: float64

Пояснення: Ми групуємо дані за колонкою Rating і обчислюємо середню суму покупки для кожної групи. Це допоможе побачити, як змінюється середній чек залежно від оцінки покупців.

In [9]:
# Відповідь на Гіпотезу 2: Час дня та витрати

# Конвертуємо час в datetime формат
df['Time'] = pd.to_datetime(df['Time'])

# Створюємо нову колонку 'Period', що відображає періоди дня (ранок, день, вечір)
df['Period'] = pd.cut(df['Time'].dt.hour, bins=[0, 12, 18, 24], labels=['Morning', 'Afternoon', 'Evening'], right=False)

# Обчислюємо середню суму покупки для кожного періоду дня
average_total_by_period = df.groupby('Period')['Total'].mean()


print(average_total_by_period)

Period
Morning      323.553982
Afternoon    326.644997
Evening      315.656157
Name: Total, dtype: float64

/tmp/ipython-input-3284059159.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Time'] = pd.to_datetime(df['Time'])
/tmp/ipython-input-3284059159.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  average_total_by_period = df.groupby('Period')['Total'].mean()

*Пояснення:* Ми розділяємо час на три періоди — ранок, день і вечір — і обчислюємо середній чек у кожному з цих періодів. Це допоможе побачити, в який час дня клієнти витрачають найбільше грошей.

In [10]:
# Відповідь на Гіпотезу 3: Тип клієнта та кількість товарів

# Обчислюємо середню кількість куплених одиниць товару для кожного типу клієнта
average_quantity_by_customer_type = df.groupby('Customer type')['Quantity'].mean()


print(average_quantity_by_customer_type)

Customer type
Member    5.558882
Normal    5.460922
Name: Quantity, dtype: float64

*Пояснення:* Ми групуємо дані за типом клієнтів (постійні або нові) і обчислюємо середню кількість придбаних товарів. Це покаже, чи постійні клієнти купують більше товарів, ніж нові покупці.

# **Використання результатів для прийняття бізнес-рішень**

1. Оцінка покупців та середній чек:

Як використовувати: Якщо середній чек значно вищий у покупців з високою оцінкою, це свідчить про те, що покращення якості обслуговування може збільшити середній чек. Бізнес може інвестувати в покращення взаємодії з клієнтами для підвищення їх задоволеності.

2. Час дня та витрати:

Як використовувати: Знання, коли клієнти витрачають більше грошей, допоможе бізнесу оптимізувати акції або знижки. Наприклад, можна запропонувати спеціальні пропозиції в періоди низьких продажів або стимулювати клієнтів робити покупки вранці чи ввечері.

3. Тип клієнта та кількість товарів:

Як використовувати: Якщо постійні клієнти купують більше товарів, варто продовжувати програми лояльності для заохочення їхніх покупок. Якщо ж нові клієнти мають меншу кількість покупок, варто розробити стратегії для залучення нових покупців і збільшення їхньої кількості товарів у кошику.